### ISSUE TITLE
Guilds does not remains

### ISSUE THREAD

**Issue by shagartz** [blaxxun-boop/Guilds#8]
If a create a guild as a user, after a logout and login it disappears.

If a create as a admin, it remains, but if a reboot the server, it disappears too

My server is hosted by Dathost, is a linux server.

**Comment by ConSolatory** [comment]
The point here is not that there are problems. There's only one problem here 
Version deception - it is indicated that the latest version is from 23 years old.  - already had problems then
Now the one who uploaded Thunder has raised the version - for advertising.
This is a dead project - it has not been working for a long time

**Comment by shagartz** [comment]
I forget to mention, it worked, it was a dathost problem, they fixed it

**Comment by blaxxun-boop** [comment]
@ConSolatory
The DLL you can download here is for the API. It's used by other mod authors to add Guild features to their mods. It doesn't do anything besides that. If you wanna use Guilds, please download the mod from https://thunderstore.io/c/valheim/p/Smoothbrain/Guilds

And yes, that works perfectly fine.
